# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Library_mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_L_MainUi(object):
    def setupUi(self, L_MainUi):
        L_MainUi.setObjectName("L_MainUi")
        L_MainUi.resize(1331, 735)
        self.centralwidget = QtWidgets.QWidget(L_MainUi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout.addWidget(self.pushButton_save)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_left.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoScrollMargin(0)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(95)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_left.addWidget(self.tableWidget)
        self.gridLayout.addLayout(self.verticalLayout_left, 0, 0, 1, 1)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 181, 651))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/book.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(199, 9, 461, 601))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_country = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_country.setObjectName("label_country")
        self.horizontalLayout_5.addWidget(self.label_country)
        self.label_scountry = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_scountry.setText("")
        self.label_scountry.setObjectName("label_scountry")
        self.horizontalLayout_5.addWidget(self.label_scountry)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_ISBN = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_ISBN.setObjectName("label_ISBN")
        self.horizontalLayout_8.addWidget(self.label_ISBN)
        self.label_sISBN = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_sISBN.setText("")
        self.label_sISBN.setObjectName("label_sISBN")
        self.horizontalLayout_8.addWidget(self.label_sISBN)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_bookname = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_bookname.setObjectName("label_bookname")
        self.horizontalLayout_7.addWidget(self.label_bookname)
        self.label_sbookname = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_sbookname.setText("")
        self.label_sbookname.setObjectName("label_sbookname")
        self.horizontalLayout_7.addWidget(self.label_sbookname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_author = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_author.setObjectName("label_author")
        self.horizontalLayout_6.addWidget(self.label_author)
        self.label_sauthor = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_sauthor.setText("")
        self.label_sauthor.setObjectName("label_sauthor")
        self.horizontalLayout_6.addWidget(self.label_sauthor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_present = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_present.setObjectName("label_present")
        self.horizontalLayout_3.addWidget(self.label_present)
        self.label_spresent = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spresent.setText("")
        self.label_spresent.setObjectName("label_spresent")
        self.horizontalLayout_3.addWidget(self.label_spresent)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_class = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_class.setObjectName("label_class")
        self.horizontalLayout_11.addWidget(self.label_class)
        self.label_sclass = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_sclass.setText("")
        self.label_sclass.setObjectName("label_sclass")
        self.horizontalLayout_11.addWidget(self.label_sclass)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_pagenum = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_pagenum.setObjectName("label_pagenum")
        self.horizontalLayout_12.addWidget(self.label_pagenum)
        self.label_spage = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spage.setText("")
        self.label_spage.setObjectName("label_spage")
        self.horizontalLayout_12.addWidget(self.label_spage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_Pyear = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_Pyear.setObjectName("label_Pyear")
        self.horizontalLayout_10.addWidget(self.label_Pyear)
        self.label_syear = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_syear.setText("")
        self.label_syear.setObjectName("label_syear")
        self.horizontalLayout_10.addWidget(self.label_syear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_price = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_price.setObjectName("label_price")
        self.horizontalLayout_4.addWidget(self.label_price)
        self.label_sprice = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_sprice.setText("")
        self.label_sprice.setObjectName("label_sprice")
        self.horizontalLayout_4.addWidget(self.label_sprice)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_right.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_addnewbook = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addnewbook.setObjectName("pushButton_addnewbook")
        self.horizontalLayout_2.addWidget(self.pushButton_addnewbook)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_right.addLayout(self.horizontalLayout_2)
        self.verticalLayout_right.setStretch(0, 6)
        self.gridLayout.addLayout(self.verticalLayout_right, 0, 1, 1, 1)
        L_MainUi.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(L_MainUi)
        self.statusbar.setObjectName("statusbar")
        L_MainUi.setStatusBar(self.statusbar)

        self.retranslateUi(L_MainUi)
        QtCore.QMetaObject.connectSlotsByName(L_MainUi)

    def retranslateUi(self, L_MainUi):
        _translate = QtCore.QCoreApplication.translate
        L_MainUi.setWindowTitle(_translate("L_MainUi", "MainWindow"))
        self.comboBox.setItemText(0, _translate("L_MainUi", "ISBN"))
        self.comboBox.setItemText(1, _translate("L_MainUi", "书名"))
        self.comboBox.setItemText(2, _translate("L_MainUi", "作者"))
        self.pushButton_search.setText(_translate("L_MainUi", "搜索"))
        self.pushButton_save.setText(_translate("L_MainUi", "保存"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("L_MainUi", "国家"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("L_MainUi", "ISBN"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("L_MainUi", "书名"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("L_MainUi", "作者"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("L_MainUi", "出版单位"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("L_MainUi", "图书分类"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("L_MainUi", "定价"))
        self.groupBox.setTitle(_translate("L_MainUi", "获取更多图书"))
        self.label_country.setText(_translate("L_MainUi", "国家"))
        self.label_ISBN.setText(_translate("L_MainUi", "I S B N"))
        self.label_bookname.setText(_translate("L_MainUi", "书    名"))
        self.label_author.setText(_translate("L_MainUi", "作    者"))
        self.label_present.setText(_translate("L_MainUi", "出版单位"))
        self.label_class.setText(_translate("L_MainUi", "图书分类"))
        self.label_pagenum.setText(_translate("L_MainUi", "页数"))
        self.label_Pyear.setText(_translate("L_MainUi", "出版年份"))
        self.label_price.setText(_translate("L_MainUi", "定价"))
        self.label_20.setText(_translate("L_MainUi", "内容介绍"))
        self.pushButton_addnewbook.setText(_translate("L_MainUi", "新建图书档案"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainwindow = QtWidgets.QMainWindow()
    Ui_L_MainUi().setupUi(Mainwindow)
    Mainwindow.show()
    sys.exit(app.exec_())
