# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_addnewbook.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(521, 518)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 211, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_isbn = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_isbn.setObjectName("label_isbn")
        self.horizontalLayout.addWidget(self.label_isbn)
        self.lineEdit_isbn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_isbn.setObjectName("lineEdit_isbn")
        self.horizontalLayout.addWidget(self.lineEdit_isbn)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_bookname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_bookname.setObjectName("label_bookname")
        self.horizontalLayout_8.addWidget(self.label_bookname)
        self.lineEdit_bookname = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_bookname.setObjectName("lineEdit_bookname")
        self.horizontalLayout_8.addWidget(self.lineEdit_bookname)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_author = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_author.setObjectName("label_author")
        self.horizontalLayout_7.addWidget(self.label_author)
        self.lineEdit_author = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.horizontalLayout_7.addWidget(self.lineEdit_author)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_classifce = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_classifce.setObjectName("label_classifce")
        self.horizontalLayout_6.addWidget(self.label_classifce)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_present = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_present.setObjectName("label_present")
        self.horizontalLayout_5.addWidget(self.label_present)
        self.lineEdit_present = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_present.setObjectName("lineEdit_present")
        self.horizontalLayout_5.addWidget(self.lineEdit_present)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_page = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_4.addWidget(self.label_page)
        self.lineEdit_page = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_page.setObjectName("lineEdit_page")
        self.horizontalLayout_4.addWidget(self.lineEdit_page)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_year = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_year.setObjectName("label_year")
        self.horizontalLayout_3.addWidget(self.label_year)
        self.lineEdit_year = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_year.setObjectName("lineEdit_year")
        self.horizontalLayout_3.addWidget(self.lineEdit_year)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_price = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_price.setObjectName("label_price")
        self.horizontalLayout_2.addWidget(self.label_price)
        self.lineEdit_price = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.horizontalLayout_2.addWidget(self.lineEdit_price)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.introduce = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.introduce.setObjectName("introduce")
        self.verticalLayout.addWidget(self.introduce)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(9, 10)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(229, 9, 282, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.button_read_internet = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.button_read_internet.setObjectName("button_read_internet")
        self.horizontalLayout_9.addWidget(self.button_read_internet)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_pixmap = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_pixmap.setText("")
        self.label_pixmap.setPixmap(QtGui.QPixmap("../../Library_mang/res/book.png"))
        self.label_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pixmap.setObjectName("label_pixmap")
        self.verticalLayout_3.addWidget(self.label_pixmap)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.pushButton_selectbook = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_selectbook.setObjectName("pushButton_selectbook")
        self.horizontalLayout_11.addWidget(self.pushButton_selectbook)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.pushButton_confirm = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout_10.addWidget(self.pushButton_confirm)
        self.pushButton_cancal = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_cancal.setObjectName("pushButton_cancal")
        self.horizontalLayout_10.addWidget(self.pushButton_cancal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_isbn.setText(_translate("Dialog", "*ISBN"))
        self.label_bookname.setText(_translate("Dialog", "*书名"))
        self.label_author.setText(_translate("Dialog", "*作者"))
        self.label_classifce.setText(_translate("Dialog", "图书分类"))
        self.label_present.setText(_translate("Dialog", "出版单位"))
        self.label_page.setText(_translate("Dialog", "页数"))
        self.label_year.setText(_translate("Dialog", "出版年份"))
        self.label_price.setText(_translate("Dialog", "定价"))
        self.introduce.setText(_translate("Dialog", "内容简介"))
        self.button_read_internet.setText(_translate("Dialog", "读取网络数据"))
        self.label_18.setText(_translate("Dialog", "封面尺度不要过于夸张\n"
"网络数据不对请自行调整"))
        self.pushButton_selectbook.setText(_translate("Dialog", "选择图书封面"))
        self.pushButton_confirm.setText(_translate("Dialog", "确认"))
        self.pushButton_cancal.setText(_translate("Dialog", "取消"))
